services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vm_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: .
    depends_on:
      - db
    ports:
      - "8888:8888"
    environment:
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: Vb24122003vb
      DB_NAME: vm_manager
    command: poetry run python server/server.py

volumes:
  postgres_data: