version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Vb24122003vb
      POSTGRES_DB: vm_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8888:8888"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: Vb24122003vb
      DB_NAME: vm_manager
    command: poetry run python -m server.server

volumes:
  postgres_data:
